### ISSUE TITLE
ExpansionTile in AddNewPlayer stopped working

### ISSUE THREAD

**Issue by GroovinChip** [GroovinChip/MySoftballTeam#2]
### **Code**
https://github.com/GroovinChip/MySoftballTeam/blob/master/lib/screens/addNewPlayer.dart

### **Stack Trace**
```
E/BpSurfaceComposerClient(10034): Failed to transact (-1)
E/BpSurfaceComposerClient(10034): Failed to transact (-1)
I/flutter (10034): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (10034): The following assertion was thrown during performLayout():
I/flutter (10034): not implemented
I/flutter (10034): 'package:flutter/src/material/input_decorator.dart': Failed assertion: line 895 pos 12: 'false'
I/flutter (10034): 
I/flutter (10034): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (10034): more information in this error message to help you determine and fix the underlying cause.
I/flutter (10034): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (10034):   https://github.com/flutter/flutter/issues/new
I/flutter (10034): 
I/flutter (10034): When the exception was thrown, this was the stack:
I/flutter (10034): #2      _RenderDecoration.computeDistanceToActualBaseline (package:flutter/src/material/input_decorator.dart)
I/flutter (10034): #3      RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1633:50)
I/flutter (10034): #4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (10034): #5      RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1633:22)
I/flutter (10034): #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:102:20)
I/flutter (10034): #7      RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1633:50)
I/flutter (10034): #8      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (10034): #9      RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1633:22)
I/flutter (10034): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:102:20)
I/flutter (10034): #11     RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1633:50)
I/flutter (10034): #12     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (10034): #13     RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1633:22)
I/flutter (10034): #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:102:20)
I/flutter (10034): #15     RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1633:50)
I/flutter (10034): #16     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (10034): #17     RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1633:22)
I/flutter (10034): #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.computeDistanceToActualBaseline (package:flutter/src/rendering/proxy_box.dart:102:20)
I/flutter (10034): #19     RenderBox.getDistanceToActualBaseline.<anonymous closure> (package:flutter/src/rendering/box.dart:1633:50)
I/flutter (10034): #20     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:277:23)
I/flutter (10034): #21     RenderBox.getDistanceToActualBaseline (package:flutter/src/rendering/box.dart:1633:22)
I/flutter (10034): #22     RenderBox.getDistanceToBaseline (package:flutter/src/rendering/box.dart:1616:27)
I/flutter (10034): #23     _RenderListTile._boxBaseline (package:flutter/src/material/list_tile.dart:720:16)
I/flutter (10034): #24     _RenderListTile.performLayout (package:flutter/src/material/list_tile.dart:779:38)
I/flutter (10034): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #26     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (10034): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (10034): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (10034): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (10034): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #34     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
I/flutter (10034): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #36     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:381:13)
I/flutter (10034): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #38     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (10034): #39     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1143:11)
I/flutter (10034): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #41     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
I/flutter (10034): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #43     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (10034): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #45     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (10034): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #47     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
I/flutter (10034): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #49     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (10034): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #51     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (10034): #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #53     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (10034): #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #55     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (10034): #56     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1143:11)
I/flutter (10034): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #58     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (10034): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #60     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (10034): #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #62     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (10034): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #64     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
I/flutter (10034): #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #66     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:381:13)
I/flutter (10034): #67     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #68     _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:479:13)
I/flutter (10034): #69     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #70     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (10034): #71     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #72     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (10034): #73     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #74     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (10034): #75     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #76     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (10034): #77     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #78     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (10034): #79     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #80     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (10034): #81     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #82     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (10034): #83     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #84     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:109:13)
I/flutter (10034): #85     RenderObject.layout (package:flutter/src/rendering/object.dart:1570:7)
I/flutter (10034): #86     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
I/flutter (10034): #87     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:399:7)
I/flutter (10034): #88     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
I/flutter (10034): #89     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
I/flutter (10034): #90     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1445:7)
I/flutter (10034): #91     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:709:18)
I/flutter (10034): #92     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter (10034): #93     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:627:13)
I/flutter (10034): #94     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (10034): #95     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (10034): #96     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (10034): #97     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (10034): #98     _invoke (dart:ui/hooks.dart:120:13)
I/flutter (10034): #99     _drawFrame (dart:ui/hooks.dart:109:3)
I/flutter (10034): (elided 2 frames from class _AssertionError)
I/flutter (10034): 
I/flutter (10034): The following RenderObject was being processed when the exception was fired:
I/flutter (10034):   _RenderListTile#3c876 relayoutBoundary=up30 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (10034):   creator: _ListTile ← MediaQuery ← Padding ← SafeArea ← Semantics ← Listener ← _GestureSemantics ←
I/flutter (10034):   RawGestureDetector ← GestureDetector ← InkWell ← ListTile ← Column ← ⋯
I/flutter (10034):   parentData: offset=Offset(0.0, 0.0) (can use size)
I/flutter (10034):   constraints: BoxConstraints(0.0<=w<=307.4, 0.0<=h<=Infinity)
I/flutter (10034):   size: MISSING
I/flutter (10034): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (10034):   RenderParagraph#3efe1 relayoutBoundary=up31 NEEDS-PAINT
I/flutter (10034):   RenderConstrainedBox#3c5c0 relayoutBoundary=up31 NEEDS-PAINT
I/flutter (10034):     RenderSemanticsAnnotations#b286b relayoutBoundary=up32 NEEDS-PAINT
I/flutter (10034):       RenderIgnorePointer#baaf7 relayoutBoundary=up33 NEEDS-PAINT
I/flutter (10034):         RenderPointerListener#b5cfd relayoutBoundary=up34 NEEDS-PAINT
I/flutter (10034):           _RenderDecoration#1f9f2 relayoutBoundary=up35 NEEDS-PAINT
I/flutter (10034): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (10034): Another exception was thrown: RenderBox was not laid out: _RenderListTile#3c876 relayoutBoundary=up30 NEEDS-PAINT
I/flutter (10034): Another exception was thrown: RenderBox was not laid out: RenderPadding#381cb relayoutBoundary=up29 NEEDS-PAINT
I/flutter (10034): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#d6b6b relayoutBoundary=up28 NEEDS-PAINT
I/flutter (10034): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#2c8cc relayoutBoundary=up27 NEEDS-PAINT
I/flutter (10034): Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#3e1df relayoutBoundary=up26 NEEDS-PAINT
I/flutter (10034): Another exception was thrown: RenderBox was not laid out: RenderFlex#2ba3f relayoutBoundary=up25 NEEDS-PAINT
I/flutter (10034): Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.
I/flutter (10034): Another exception was thrown: NoSuchMethodError: The method '>' was called on null.
I/flutter (10034): Another exception was thrown: RenderBox was not laid out: RenderFlex#2ba3f relayoutBoundary=up25
I/flutter (10034): Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.
I/flutter (10034): Another exception was thrown: NoSuchMethodError: The method '>' was called on null.
```

**Comment by GroovinChip** [comment]
Changed the children of the ExpansionTile to be SizedBoxes that take up the whole width of the parent. For some reason this works. I'd rather use the ListTiles, but hey, whatever works I guess...
